package com.example.materialdesignpratica.ui.theme
import androidx.compose.ui.graphics.Color


//TEMA CLARO
val primaryLight = Color(0xFF2D628B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFCDE5FF)
val onPrimaryContainerLight = Color(0xFF001D32)
val secondaryLight = Color(0xFF51606F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD4E4F6)
val onSecondaryContainerLight = Color(0xFF0D1D2A)
val tertiaryLight = Color(0xFF67587A)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFEDDCFF)
val onTertiaryContainerLight = Color(0xFF221533)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF7F9FF)
val onBackgroundLight = Color(0xFF181C20)
val surfaceLight = Color(0xFFF7F9FF)
val onSurfaceLight = Color(0xFF181C20)
val surfaceVariantLight = Color(0xFFDEE3EB)
val onSurfaceVariantLight = Color(0xFF42474E)
val outlineLight = Color(0xFF72787E)
val outlineVariantLight = Color(0xFFC2C7CE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3135)
val inverseOnSurfaceLight = Color(0xFFEEF1F6)
val inversePrimaryLight = Color(0xFF9ACCFA)

//TEMA ESCURO
val primaryDark = Color(0xFF9ACCFA)
val onPrimaryDark = Color(0xFF003352)
val primaryContainerDark = Color(0xFF094A72)
val onPrimaryContainerDark = Color(0xFFCDE5FF)
val secondaryDark = Color(0xFFB8C8DA)
val onSecondaryDark = Color(0xFF233240)
val secondaryContainerDark = Color(0xFF394857)
val onSecondaryContainerDark = Color(0xFFD4E4F6)
val tertiaryDark = Color(0xFFD2BFE7)
val onTertiaryDark = Color(0xFF382A4A)
val tertiaryContainerDark = Color(0xFF4F4061)
val onTertiaryContainerDark = Color(0xFFEDDCFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101418)
val onBackgroundDark = Color(0xFFE0E2E8)
val surfaceDark = Color(0xFF101418)
val onSurfaceDark = Color(0xFFE0E2E8)
val surfaceVariantDark = Color(0xFF42474E)
val onSurfaceVariantDark = Color(0xFFC2C7CE)
val outlineDark = Color(0xFF8C9198)
val outlineVariantDark = Color(0xFF42474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E2E8)
val inverseOnSurfaceDark = Color(0xFF2D3135)
val inversePrimaryDark = Color(0xFF2D628B)