openapi: 3.0.0
info:
  title: API de Gerenciamento de Usuários
  description: API para criar, listar, atualizar e excluir usuários
  version: 1.0.0
servers:
  - url: http://localhost:8081
paths:
  /user/register:
    post:
      summary: Criar um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '201':
          description: Usuário criado com sucesso
        '400':
          description: Requisição inválida ou dados do usuário faltantes
  /user/delete/{id}:
    delete:
      summary: Excluir um usuário pelo ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID do usuário a ser excluído
      responses:
        '200':
          description: Usuário excluído com sucesso
        '404':
          description: Usuário não encontrado
  /user/search/{id}:
    get:
      summary: Obter detalhes de um usuário pelo ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID do usuário a ser recuperado
      responses:
        '200':
          description: Detalhes do usuário obtidos com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: Usuário não encontrado
  /user/edit/{id}:
    patch:
      summary: Atualizar um usuário pelo ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID do usuário a ser atualizado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Usuário atualizado com sucesso
        '400':
          description: Requisição inválida ou dados do usuário faltantes
        '404':
          description: Usuário não encontrado
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: objectId
          description: ID do usuário
        name:
          type: string
          description: Nome do usuário
        email:
          type: string
          format: email
          description: Email do usuário
        password:
          type: string
          description: Senha do usuário
    UserRequest:
      type: object
      properties:
        name:
          type: string
          description: Nome do usuário
        email:
          type: string
          format: email
          description: Email do usuário
        password:
          type: string
          description: Senha do usuário
    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: objectId
          description: ID do usuário
        name:
          type: string
          description: Nome do usuário
        email:
          type: string
          format: email
          description: Email do usuário
        password:
          type: string
          description: Senha do usuário
